### ISSUE TITLE
Adapter operations not thread-safe

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery-adapter-library#32]
**Description**

Operation responsible for creating the adapter clients uses viper internally which is not thread safe hence concurrently accessing the function results in a go "panic".

**Expected Behavior**

Creating the adapter clients should be thread safe.

**Screenshots**

**Environment:**
 - OS: Manjaro Linux

---
**To Reproduce**
1. Trying to create the adapter clients in a loop, that should be enough to reproduce the issue

**Comment by mgfeller** [comment]
@utkarsh-pro I'm not quite sure I understand which clients and functions you are referring to. Could you please clarify? When are these clients created concurrently?

**Comment by utkarsh-pro** [comment]
Apologies for vague description @mgfeller. Here is the detailed description of the issue:

When https://github.com/layer5io/meshery-adapter-library/blob/master/adapter/configure.go#L18 is invoked then it internally calls https://github.com/layer5io/meshery-adapter-library/blob/master/adapter/configure.go#L106 which internally uses viper. Viper's operations are by design not thread safe (https://github.com/spf13/viper/blob/master/viper.go#L1406). So whenever either the grpc requests are too quick (or made in a non-blocking manner, i.e concurrently) then the adapter crashes because multiple threads try to perform r/w on the same map.

**Comment by mgfeller** [comment]
@utkarsh-pro thanks for the clarification! Interesting challenge, if I have time, I might have a look, starting by writing a test. 
Open for anyone to pick, of course.

**Comment by mgfeller** [comment]
I'll have a go at this. Feel free to contact me if you'd rather work on that :smile:

**Comment by mgfeller** [comment]
@utkarsh-pro I wonder, in your use case (is it related to patterns?), are you calling `CreateMeshInstance` before each and every `ApplyOperation` call?

**Comment by leecalcote** [comment]
Gents, did we ever guarantee that adapters can process multiple operations simultaneously? // @kumarabd

**Comment by kumarabd** [comment]
I am technically confident that it is thread safe, haven't tested them though. The ApplyOperation() executes every operation in a new go-routine, which is why I'm confident about the thread safe behaviour. // @leecalcote @mgfeller @utkarsh-pro

**Comment by utkarsh-pro** [comment]
> I am technically confident that it is thread safe, haven't tested them though. The ApplyOperation() executes every operation in a new go-routine, which is why I'm confident about the thread safe behaviour. // @leecalcote @mgfeller @utkarsh-pro

@kumarabd `ApplyOperation` is not thread unsafe, rather `CreateInstance` is the culprit. Meshery server calls the `CreateInstance` every time before invoking `ApplyOperation`, which makes it also unsafe. The reason meshery server calls `CreateInstance` everytime before invoking `ApplyOperation` is because it doesn't keeps track if it has already created an instance earlier or not. Ideally, meshery server should have access to an adapter instance singleton which is guaranteed to be not-nil (This approach will have its downside too, stale info of an adapter availability being the prominent one) . But these guarantees on the meshery server should be independent of the thread safe or unsafe nature of the adapter. I think we should wrap the viper as well as in memory provider operations in RWMutex to avoid such issue :sweat_smile:
