### ISSUE TITLE
Error when deprovisioning system default namespaces

### ISSUE THREAD

**Issue by kumarabd** [meshery/meshery-adapter-library#49]
**Description**

Handle de-provisioning for system default namespaces. 

Namespaces to handle:
- default
- kube-system
- kube-public

On a different note this can also be handled with the type of error returned, basically - 
https://pkg.go.dev/k8s.io/apimachinery/pkg/api/errors#IsNotAcceptable

**Comment by leecalcote** [comment]
// @houshym

**Comment by debjani1413** [comment]
@kumarabd I would like to give it a try, but before that could you please be a little elaborate on how to get started on this??

**Comment by Shreyas220** [comment]
@leecalcote sorry for getting to this late, i was out of station
was looking into this on my way home 
deprovisioning of any adapter is handled through meshkit, also as we are using helm as a standard for installation, deletion is being handled [here ](https://github.com/layer5io/meshkit/blob/bff5ad239e82623a18055bcc9c25ad962c85d6fb/utils/kubernetes/apply-helm-chart.go#L378)
i don't think this even needs to be handled 
please let me know otherwise
